### ISSUE TITLE
No quest rewards

### ISSUE THREAD

**Issue by mushiden** [aaronhowser1/Infinity-Evolved-Expert-Mode-HQM#2]
Hi
I personally like playing HQM with quest rewards. 
I've added some basic rewards to It's Like a Whole New Game.
They mostly make things less tedious.

Are you open to a pull request that adds rewards?

**Comment by aaronhowser1** [comment]
Is it possible to make 2 separate versions, one with and one without quest rewards? (I'm still not 100% on how GitHub works.) While I was making the quests for Requiem HQM, I was asked by a bunch of people to remove quest rewards.

**Comment by emeralis00** [comment]
You could look into git branching, which would functionally let you have multiple versions of the code at once. Just don't merge the second branch with the quest rewards into the master branch and you're good.

**Comment by TheFlash787** [comment]
Hey, Adding quest rewards to the mod would be fantastic, It allows the pack to reward us for all the tedious tasks (Obviously not OP rewards like Ozone). I was stunned to see that HQM was released into the pack on an update but after such a long duration of time without updates, I was a little disappointed to see how there were no rewards and seemed a little rushed. 

Making two seperate versions (one with and one without) would give players and server staff the choice to decide whether to add rewards or not. 

Thanks

**Comment by Sandstroem** [comment]
I think quest rewards like the one you did with the lasers are a good way. So basically, make one laser, get five for free. That is not really gamebreaking, since you make more anyway, but gives players a nice reward. You could try to add more of these. For some of the machines you could give some items, that are either used in their recipe and will be used later on, or some of the stuff they produce.
So for example quest says "make one IC2 metal former" and the reward would be a IC2 machine case or some iron plates or so.

**Comment by aaronhowser1** [comment]
I just went through a bunch of quests adding rewards. Here's my little text document changelog thing so far:

Forge Hammer quest gives 1 Machine Casing

First 2 Botania quests give 8 Floral Fertilizer

First Thaumcraft quest gives 8 of a random Mana Bean

Third Botania quest gives option of 16 Floral Fertilizer or 1 Blacker Lotus (10% of a Mana Pool)

Witches Oven quest has rewards of either 1 Fume Funnel or 16 Clay Jars

Added 3 Regen II potions to the Blood Altar quest

Added 4 Blacker Lotuses to the Elven Gateway quest

Added option of either Strength II, Regen II, or Resistance II Vials to the Gaia Guardian quest

Added 5 Aura Nodes to the Icorcloth wand quest
