### ISSUE TITLE
The Vat

### ISSUE THREAD

**Issue by RanceMohammitz** [aaronhowser1/Infinity-Evolved-Expert-Mode-HQM#5]
The vat quest has no goal (no option to submit The Vat)

**Comment by aaronhowser1** [comment]
This is going to be fixed in the next version. If you don't want to wait for the next Infinity update, you can download it from the main page (or click [this](https://github.com/aaronhowser1/Infinity-Evolved-Expert-Mode-HQM/archive/master.zip)) and install it manually.
